version: 2

multi-ecosystem-groups:
  dependencies:
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Berlin"

updates:
  - package-ecosystem: "npm"
    directory: "/"
    patterns:
      - "*"
    multi-ecosystem-group: "dependencies"
    labels:
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    patterns:
      - "*"
    multi-ecosystem-group: "dependencies"
    labels:
      - "dependencies"
